# Generated by Django 3.2.8 on 2021-10-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='fingerprint',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='exam_num',
            new_name='examnumber',
        ),
        migrations.AddField(
            model_name='register',
            name='province',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
